// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PawledgerAPI.Context;

namespace PawledgerAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("PawledgerAPI.Entities.MedicalHistoryEntity", b =>
                {
                    b.Property<string>("MedicalHistoryId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTs")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PetTokenId")
                        .HasColumnType("text");

                    b.Property<string>("ResponseBytes")
                        .HasColumnType("text");

                    b.Property<string>("TokenId")
                        .HasColumnType("text");

                    b.HasKey("MedicalHistoryId");

                    b.HasIndex("PetTokenId");

                    b.ToTable("MedicalHistory");
                });

            modelBuilder.Entity("PawledgerAPI.Entities.PetEntity", b =>
                {
                    b.Property<string>("TokenId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedTs")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("TokenId");

                    b.ToTable("Pet");
                });

            modelBuilder.Entity("PawledgerAPI.Entities.MedicalHistoryEntity", b =>
                {
                    b.HasOne("PawledgerAPI.Entities.PetEntity", "Pet")
                        .WithMany()
                        .HasForeignKey("PetTokenId");

                    b.Navigation("Pet");
                });
#pragma warning restore 612, 618
        }
    }
}
